export const OWNER_COMMANDS = Object.freeze([
  "setup",
  "status",
  "update",
  "uninstall",
  "doctor",
  "daemon",
  "logs",
  "logs purge",
  "diagnostics create",
  "diagnostics inspect",
]);
export const AGENT_COMMANDS = Object.freeze(["send", "reply", "inbox get"]);
export const COMMAND_SCHEMAS = Object.freeze({
  send: Object.freeze([
    "--subject",
    "--body",
    "--body-file",
    "--idempotency-key",
    "--json",
    "--help",
    "--help-json",
  ]),
  reply: Object.freeze([
    "--thread",
    "--body",
    "--body-file",
    "--idempotency-key",
    "--json",
    "--help",
    "--help-json",
  ]),
  "inbox get": Object.freeze(["--thread", "--json", "--help", "--help-json"]),
  status: Object.freeze(["--agent-safe", "--json", "--help", "--help-json"]),
  update: Object.freeze(["--json", "--help", "--help-json"]),
  doctor: Object.freeze(["--deep", "--json", "--help", "--help-json"]),
  setup: Object.freeze(["--json", "--help", "--help-json"]),
  uninstall: Object.freeze(["--json", "--help", "--help-json"]),
  daemon: Object.freeze(["--foreground", "--json", "--help", "--help-json"]),
  logs: Object.freeze(["--limit", "--json", "--help", "--help-json"]),
  "logs purge": Object.freeze(["--json", "--help", "--help-json"]),
  "diagnostics create": Object.freeze(["--json", "--help", "--help-json"]),
  "diagnostics inspect": Object.freeze([
    "--id",
    "--json",
    "--help",
    "--help-json",
  ]),
});
